- osfoffline/alerts.py
- osfoffline/application/background.py
- osfoffline/database_manager/db.py
- osfoffline/database_manager/utils.py
- osfoffline/polling_osf_manager/polling.py
- osfoffline/settings.py
- tasks.py
Move commonly changed settings (like RECHECK_TIME and log level) into a single place to aid configuration.
Also begin work on a DEV_MODE flag, which would cause the client to work with a local copy of the OSF (instead of staging) and output more verbose log messages. This feature does not yet work; will talk to Himanshu about what waterbutler instance to use in the AM.
> Centralize settings to aid development

- osfoffline/polling_osf_manager/osf_query.py
previously the issue was that I was using the move action for OSF Api's move endpoint. The move action also did allow for renaming files (very original design). However, I was messing something up in creating the path for the request. Instead of fixing the path, I changed it so we use the much simpler rename action. This does not require fixing the path.
> simplified move code

- osfoffline/views/system_tray.py
Refs https://openscience.atlassian.net/browse/OSF-5101
Fixes an issue where the system tray icon is an empty box on Mac OS (and possibly windows)
It appears that in the process of cleaning up imports, we removed one that wasn't used in *code*, but was required in order for QT to find and use assets.
> Restore system tray icon on Mac os

- osfoffline/polling_osf_manager/api_url_builder.py
Purpose
-----------
Remove registrations from the nodes list.
Changes
-------------
Update api_url_for to add a query argument to the /users/me/nodes request. I'm not sure if I dealt with the trailing slash in the most efficient way, but it works and will be fine as long as we don't need additional query parameters added outside of that part of the code. You'll need to sync with OSF Develop as of around 11 this morning to test locally, but it's on staging.
Side effects
----------------
None.
> Don't get registrations with the users/nodes

- osfoffline/database_manager/models.py
- osfoffline/views/start_screen.py
Fix an error reported by @nicipfeiffer  and @NatashaRichter in which trying to log out (then in as a different user) would give a database-related error message. ("Unable to save user data; please try again later")
Disabled the `osf_login` field of the database model. It is intended to only contain an email address, and in the absence of that data, every single user was being given the same placeholder value. 
Since this violated the `unique` constraint on that field, users were seeing an error message.
Didn't update the tests- they were already broken, and likely will remain so until after this field is needed again. (we will begin collecting email addresses as part of #26 )
> Fix DB error when two users share a computer 

- osfoffline/views/preferences.py
Purpose
-
Previously a user would not be notified that they had not saved their changes when select which projects should be synced and which to ignore.  This meant that a user may make a bunch of changes, close out of the window, and then be confused as to why nothing was being synced.  This PR seeks to address this issue by opening a window alerting the user that they have unsaved changes (if applicable)
Changes
-
First I added a list field to the class to keep track of which projects were checked the last time the project was saved.  Then I bumped the code that creates guid_list out into its own method and called this inside of closeEvent and compared to the list of checked projects from the last save.  If they were equal, preferences closes normally, otherwise a message box pops up …
> [Feature] Alert user that they have not saved changes

- osfoffline/utils/path.py
- osfoffline/views/preferences.py
Purpose
-
Previously there was a double for loop comparing tree item names with node names to link the two together.  This poses two problems:
1) It is O(n^2) time when it could be O(n) and this is slow with large numbers of nodes.
2) If two nodes have the same name it may link the wrong things
Changes
-
Changed tree_items to be a list of tuples so that the first tuple index is the tree_item and the second is the node id.  This allows us to do one loop and then get the part we need and they will always be linked together properly.
Side Effects
-
Should not be any because everything should be linked properly.
[#OSF-5152]
> Refactored preferences to no longer use node name as a dependancy

- osfoffline/filesystem_manager/osf_event_handler.py
Purpose
======
Close previously unknown bug. When a file is modified, the OS typically uses temp files. In many cases, this causes what should be viewed as a modify event to be a delete event, presumably because the original file is deleted and the temp file is renamed to the original file in one action.
Changes
=======
On delete, sleep for a second to make sure any filesystem changes are finished, then check to see if the file still exists on disk. If it does, don't delete it remotely.
Side Effects
=========
None
> [Feature] Don't delete on modify

- osfoffline/views/preferences.py
Purpose
-
self.tree_items changed to a list of tuples and this code did not merge well with it as a result.  This code fixes that error
Changes
-
Changed the code to expect a tuple
Side effects
-
Should be none since there was barely any change
> Fix for sync all/sync none

- osfoffline/polling_osf_manager/polling.py
Only create 'component' folder when the nodes actually has a child node. fixes https://openscience.atlassian.net/browse/OSF-5145
> make component folder only show up when ther is child node

- osfoffline/database_manager/models.py
- osfoffline/filesystem_manager/osf_event_handler.py
- osfoffline/utils/path.py
Purpose
======
On the OSF, you can have two projects with the same name. In a filesystem, having two directories of the same name in the same location doesn't work as well. 
Changes
=======
Append node/folder ID from the OSF to the name when creating a folder path
Side Effects
=========
* Improved logging for a `todo handle exception`.
* None found during testing. (But other unrelated bugs uncovered during testing)
[#OSF-4408]
> [Feature][Fix] unique project folder names

- osfoffline/database_manager/models.py
Small fix, self-explanatory.
OSF doesn't allow two folders in the same directory to have the same name, no need for OSFO to.
> Only append ID for project level folders

- osfoffline/filesystem_manager/osf_event_handler.py
Purpose
remove the unnecessary warning 
Side Effect
Need to teach user in the training session that don't name any folder components.
[#OSF-5097]
> get rid of the unnecessary warnning

- osfoffline/views/preferences.py
- osfoffline/views/rsc/gui/preferences_gui/preferences.ui
- osfoffline/views/rsc/preferences_rc.py
- osfoffline/views/system_tray.py
Purpose
-
* Renamed 'Preferences' to 'Settings'
* Changed 'Update' button to 'Apply Settings'
* Made the 'Apply Settings' button close the 'Settings' window
* Fixed issued where the loading cursor would stay forever the second time you opened the settings window
Changes
-
* Basic renaming changes in preferences.ui/preferences_rc.py using QT Creator.
* In preferences.py added a call to close the window when the 'Apply Settings' button is clicked.
* Moved around some code and added a check to see whether the tree has been populated yet or not to handle the cursor error
Side Effects
-
Due to the fact that these are all UI changes basically there should be no side effects.
[#OSF-5167]
> Preferences panel UI Changes

- osfoffline/filesystem_manager/osf_event_handler.py
Purpose
=======
Prevent application from crashing when it could just ignore a file.
Changes
=======
Alerts the user that something went wrong whenever sync fails for file operations, and logs the exception.
Similar to https://github.com/CenterForOpenScience/OSF-Offline/pull/63
[#OSF-5194]
> Exception handling for bad local files

- osfoffline/polling_osf_manager/polling.py
Purpose
=======
Allow multiple uploads. You can only key one thing to `None`, and if a file is newly created locally, it won't have an `osf_id` until it's pushed to the OSF.
Changes
=======
Ensure all such files are added to the tuple list.
Side Effects
==========
None
> [Fix]Allow multiple uploads

- osfoffline/polling_osf_manager/polling_events.py
Fixes bug reported by Nici: "Local variable 'resp' referenced before assignment" when download operation throws an exception
```
[2015-11-17 06:39:12,646][Thread-10][polling_events.py][WARNING][root]: Bad Internet Connection
[2015-11-17 06:39:12,649][Thread-10][base_events.py][ERROR][asyncio]: Exception in callback Poll.handle_exception(<Task finishe...assignment",)>)
handle: <Handle Poll.handle_exception(<Task finishe...assignment",)>)>
Traceback (most recent call last):
File "c:\python343\lib\asyncio\events.py", line 120, in _run
File "C:\Users\IEUser\Documents\GitHub\OSF-Offline\osfoffline\polling_osf_manager\polling.py", line 74, in handle_exception
File "c:\python343\lib\asyncio\tasks.py", line 238, in _step
File "C:\Users\IEUser\Documents\GitHub\OSF-Offline\osfoffline\polling_osf_man …
```
> If server request throws exception,  don't try to download file

- osfoffline/polling_osf_manager/osf_query.py
Refs [#OSF-5131]. This PR fixes an error that would be encountered when moving a file from a subfolder to a parent directory.
Forked from #60 per discussion with @himanshuo
> Fix issue with moving file to a parent folder

- osfoffline/database_manager/__init__.py
- osfoffline/database_manager/db.py
- osfoffline/utils/authentication.py
- osfoffline/views/preferences.py
Purpose
=======
If a second user tries to log in, drop all db models relating to first, and allow login
Changes
=======
* Support for above
* Helper fucntion that drops db without causing the next `save` to raise errors
Side Effects
==========
None
> [Feature] Drop first user on login of second

- osfoffline/polling_osf_manager/polling.py
Purpose
======
If a download fails, we should try to download it on subsequent syncs.
Changes
=======
A failed download will be retried on next sync
Side effects
=========
A file that was deleted when OSFO was not watching will be redownloaded (probably desired behavior)
Test Notes
---------------
Some fixes have gone in to limit the number of failed downloads, but it's still possible in the case of a failed connection, and possibly other cases. In any case, when a `File` object is successfully added to the database but not the filesystem, we should retry the download.
1) I un-fixed the bug from #75 for testing, but disconnecting wifi in the middle of a sync should work just as well. With several failed downloads, there should be log statements similar to `file {filename} not reuploaded …
> [Feature]Redownload file if it is expected to be there

- osfoffline/polling_osf_manager/polling_events.py
`shutil` automatically uses attack prevention if it can (OSX)
We want it to still remove stuff if it can't (Win32)
> Remove symlink attack prevention

- osfoffline/settings/defaults.py
Risk mitigation for prod data, should only have those urls in local.py
> Point to test.osf.io

- osfoffline/client/osf.py
- osfoffline/gui/qt/preferences.py
Fix an issue where the application would crash when viewing list of nodes to sync, if a user owned any registrations.
Modified the API call to exclude any registrations from the list of user nodes.
Currently, the API attempts to act on data that may not have been returned from the server. Preferences/py does not currently handle exceptions correctly; that should be fixed separately as part of a broader error handling task.
For now, just changed logging so that we capture the traceback correctly.
> Exclude registrations from API request

- osfoffline/gui/qt/tray.py
- osfoffline/settings/defaults.py
- osfoffline/tasks/notifications.py
Refs https://openscience.atlassian.net/browse/OFF-48
Consolidate close-spaced notifications together. Give the user one message, instead of 10.
As is, this doesn't apply any special logic to the grouping. It simply grabs all notifications that occur in a certain span of time. There is an assumption that anything in `notification_queue` must be a file or folder sync operation. CRUD operations are grouped together in a single counter. See notification center screenshot below for example.
- When a notification fires, wait several seconds and gather all notifications together in a burst. Ensures that the user never has to wait too long for feedback on progress by using a straight timer; may implement debounce option later.
- INFO messages can be grouped, but messages of a higher severity will …
> [review] Basic implementation of consolidated notifications

- osfoffline/gui/qt/tray.py
<b>Purpose</b>
Fix the log out button of the system tray menu. Now it logs out the user and pop the log in screen instead of quit the application.
solves https://openscience.atlassian.net/browse/OFF-66
Also related to issue https://openscience.atlassian.net/browse/OFF-65 for fixing the logout function. Review and merge this pr in first will save some of @abought 's work.
> gix the log out button

- osfoffline/database/models.py
- osfoffline/sync/local.py
- osfoffline/tasks/operations.py
- osfoffline/tasks/queue.py
- osfoffline/utils/__init__.py
- osfoffline/utils/singleton.py
Refs [OFF-62](https://openscience.atlassian.net/browse/OFF-62)
Address problems with sync functionality on Windows operating systems.
- Replace several hardcoded OS-specific path separators with `os.path.sep`.
- Fixes issue where first sync attempt lead to `parent is None` errors, and subsequent attempts lead to database integrity errors
- Add docstrings to clarify differences between methods.
- This appears to be tied to the conflict resolution mechanism: it can be created with a forward slash in the path, but the auditor tries to find a DB object based on file path (not an exact string match), then creates a File object with a specific OSF id. (the file object was actually there, but not found by the auditor)
> Fix windows sync issues

- osfoffline/tasks/operations.py
Codes were moved from 2 to 3, but again from 3.4 to 3.5. This should use the backwards-compatible recommendation for 3.4.
https://docs.python.org/3/library/http.html#http.HTTPStatus
> Fix http imports again (3.4 vs 3.5 changes)

- osfoffline/sync/ext/watchdog.py
Windows sends an update event immediately after a create/move event in some cases. Tweak consolidation to get rid of the extra event.
(prevent duplicate OSF traffic for spurious "updates" being sent to the server, and potentially simplify for some failing unit tests due to windows watchdog differences)
> Consolidate redundant update events

- osfoffline/gui/qt/preferences.py
Sort projects in alphabetical order in settings
Sort by title on each node in the tree list 
None, `sorted` doesn't sort in place but returns a new list.
[OFF-15]
> Sort projects in alphabetical order in settings

- osfoffline/application/background.py
- osfoffline/client/osf.py
- osfoffline/gui/qt/login.py
- osfoffline/sync/local.py
- osfoffline/sync/remote.py
- osfoffline/tasks/queue.py
We should find a way to shut down the RemoteSyncWorker and OperationWorker without waiting for their queues to be flushed. When a user logs out we're dropping the database anyways, and letting the sync operations finish adds unnecessary work and delay to the logout process. 
see: 
https://openscience.atlassian.net/browse/OFF-85
https://openscience.atlassian.net/browse/OFF-86
tldr: deleting a project that was synced locally would cause the remote sync loop to hang
- add ClientLoadError as a generic exception for API requests that fail for some reason
- try/except Node loads in RemoteSyncWorker's#_preprocess_node, and explicitly hander 4XX status codes
- some other cleanup from https://github.com/CenterForOpenScience/OSF-Offline/pull/125, in particular with consolidation/unification of how …
> [RFR] Handle remote deletion of resources

- osfoffline/tasks/operations.py
Display the name of the file/dir deleted, not the object representation.
[OFF-93]
> Don't display Python Object in notification

- osfoffline/tasks/queue.py
For long file paths, this notification used to be unreadable.
Tested in the console but couldn't get it to trigger in-app.
> Improve "error updating file" notification
